# Generated by Django 4.2 on 2023-07-15 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='slug')),
                ('message_preview', models.ImageField(blank=True, null=True, upload_to='message_preview/', verbose_name='Превью')),
                ('message_heading', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('date_of_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(default=datetime.date.today, verbose_name='Дата последнего изменения')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
                'ordering': ('message_heading',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150, verbose_name='ФИО')),
                ('client_comment', models.CharField(blank=True, max_length=350, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный клиент')),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенеты сервиса',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_message', models.CharField(default='сообщение', max_length=150, unique=True, verbose_name='Тема сообщения')),
                ('body_message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст сообщения')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='почта_пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status_mailing', models.BooleanField(default=False, verbose_name='Статус рассылки')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='почта_пользователя')),
                ('head_message', models.OneToOneField(default='сообщение', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Тема сообщения')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('status_mailing', models.BooleanField(default=False, verbose_name='Статус попытки')),
                ('get_server_mail', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ сервера')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='почта_пользователя')),
                ('head_message', models.OneToOneField(default='сообщение', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Тема сообщения')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
